### ISSUE TITLE
status': 302, 'content-security-policy-report-only': 

### ISSUE THREAD

**Issue by joluruba** [NordeaOSS/esp.bitbucket#1]
hello, i´m new using your collection, I am trying to create a new project, but I am getting the following error:
 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to retrieve the repository data which matches the supplied projectKey `PRUEB` and repositorySlug `Prueba_Maven`: {'url': 'https://bitbucket.org/.....user...../rest/api/1.0/projects/PRUEB/repos/Prueba_Maven', 'status': 302, 'content-security-policy-report-only': \"script-src 'unsafe-eval' 'strict-dynamic' 'unsafe-inline' 'self' http: https: https://d301sr5gafysq2.cloudfront.net; style-src 'self' 'unsafe-inline' https://aui-cdn.atlassian.com https://d301sr5gafysq2.cloudfront.net; report-uri https://web-security-reports.services.atlassian.com/csp-report/bb-website; default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: *; connect-src bitbucket.org *.bitbucket.org bb-inf.net *.bb-inf.net id.atlassian.com analytics.atlassian.com as.atlassian.com api-private.stg.atlassian.com api-private.atlassian.com cofs.staging.public.atl-paas.net cofs.prod.public.atl-paas.net intake.opbeat.com api.media.atlassian.com api.segment.io xid.statuspage.io xid.atlassian.com xid.sourcetreeapp.com bam.nr-data.net bam-cell.nr-data.net sentry.io bqlf8qjztdtr.statuspage.io https://d301sr5gafysq2.cloudfront.net; object-src about:; base-uri 'self'\", 'server': 'nginx', 'vary': 'Origin', 'cache-control': 'no-cache, no-store, must-revalidate, max-age=0', 'content-type': 'text/html; charset=utf-8', 'x-b3-traceid': '3e4eabe1766f9724', 'x-usage-output-ops': '0', 'x-dc-location': 'Micros', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'date': 'Sun, 19 Sep 2021 09:05:46 GMT', 'x-usage-user-time': '0.031928', 'x-usage-system-time': '0.003673', 'location': '/account/signin/?next=%2F...user...%2Frest%2Fapi%2F1.0%2Fprojects%2FPRUEB%2Frepos%2FPrueba_Maven', 'expires': 'Sun, 19 Sep 2021 09:05:46 GMT', 'x-served-by': '26159a2190b8', 'x-static-version': 'b32b6c8a21a3', 'x-render-time': '0.142847061157', 'connection': 'close', 'x-usage-input-ops': '0', 'x-version': 'b32b6c8a21a3', 'x-frame-options': 'SAMEORIGIN', 'x-request-count': '2993', 'content-length': '0', 'msg': 'HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.\\nThe last 30x error message was:\\nFound', 'body': b''}"}

With others modules like bitbucket_project_info i obtain the same error, 
Can you help me about that? thanks

**Comment by psmola** [comment]
Hi,
Please describe your environment. From logs I may infer that you use Bitbucket Cloud .

Regards,
Pawel

**Comment by yusepe42** [comment]
hello, 
I am trying to manage repositories from https://bitbucket.org/, I want to create, delete, manage, etc those repositories
Thanks

**Comment by psmola** [comment]
Hi
Ansible modules exposed in collection https://galaxy.ansible.com/esp/bitbucket support "Server" and "Data Center" hosting version of Bitbucket. Unfortunately Cloud hosting  option is not supported ( different API ) by our collection. 

Regards,
Pawel

**Comment by yusepe42** [comment]
Hi, I´m using cloud version :( , but I have install a Server version 
to test it and works fine ;) , good job

**Comment by klewan** [comment]
Closing the issue since it's related to Cloud which the collection does not support.
