### ISSUE TITLE
Status - Contributions

### ISSUE THREAD

**Issue by haxorof** [NordeaOSS/esp.bitbucket#2]
Just want to know if this is still active and can receive contributions? I looked into this role recently and found some bugs and did some additions in a fork I did.

Cheers!
Björn

**Comment by kmf** [comment]
@haxorof I think you should fork it, I'll use yours

**Comment by haxorof** [comment]
> @haxorof I think you should fork it, I'll use yours
> 

Yes, seems this project is a bit dead so then maybe I continue on my fork and merge my changes to my master branch instead of this.
